/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotecaswing;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author const
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    private DefaultTreeModel modelo;
    private DefaultMutableTreeNode nodoSeleccionado;
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        txtNuevoNodo = new javax.swing.JTextField();
        btninsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtNodoSeleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btneliminar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 430));

        jButton1.setText("Cargar Modelo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 170, 40));

        txtNuevoNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoNodoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuevoNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, 30));

        btninsertar.setText("Insertar");
        btninsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertarMouseClicked(evt);
            }
        });
        getContentPane().add(btninsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, 40));

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, 40));

        txtNodoSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodoSeleccionadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNodoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        jLabel1.setText("Nodo seleccionado: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel2.setText("Nodo Nuevo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        btneliminar1.setText("Eliminar");
        btneliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminar1MouseClicked(evt);
            }
        });
        getContentPane().add(btneliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNuevoNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoNodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoNodoActionPerformed

    private void txtNodoSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodoSeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodoSeleccionadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        modelo = new DefaultTreeModel (new DefaultMutableTreeNode ("raiz"));
        arbol.setModel(modelo);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btninsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertarMouseClicked
        // TODO add your handling code here:
        String texto=this.txtNuevoNodo.getText();
        DefaultMutableTreeNode n = new DefaultMutableTreeNode(texto);
        if(nodoSeleccionado != null){
            modelo.insertNodeInto(n, nodoSeleccionado, nodoSeleccionado.getChildCount());}
    }//GEN-LAST:event_btninsertarMouseClicked

    private void arbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolValueChanged
        // TODO add your handling code here:
        nodoSeleccionado = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        if(nodoSeleccionado != null){
        txtNodoSeleccionado.setText((String) nodoSeleccionado.getUserObject());
        }
    }//GEN-LAST:event_arbolValueChanged

    private void btneliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminar1MouseClicked
        // TODO add your handling code here:
        if(nodoSeleccionado != null){
        modelo.removeNodeFromParent(nodoSeleccionado);
        }
    }//GEN-LAST:event_btneliminar1MouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        if(nodoSeleccionado != null){
            nodoSeleccionado.setUserObject(this.txtNodoSeleccionado.getText());
            modelo.nodeChanged(nodoSeleccionado);
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNodoSeleccionado;
    private javax.swing.JTextField txtNuevoNodo;
    // End of variables declaration//GEN-END:variables
}
